In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import datetime
import tqdm

print(datetime.datetime.now().isoformat())

2025-06-17T19:02:55.806993

In [3]:
import bioacoustics_model_zoo as bmz

2025-06-17 19:10:08.400853: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-06-17 19:10:27.460505: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-06-17 19:10:28.844310: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-06-17 19:10:29.816025: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-06-17 19:10:32.174964: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-06-17 19:11:10.717747: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

In [4]:
from pathlib import Path

audio = sorted(Path("~/scratch/birdclef/raw/birdclef-2024/train_audio/asbfly").expanduser().glob("*.ogg"))[
    :2
]
audio

[PosixPath('/storage/home/hcoda1/7/acheung46/scratch/birdclef/raw/birdclef-2024/train_audio/asbfly/XC134896.ogg'),
 PosixPath('/storage/home/hcoda1/7/acheung46/scratch/birdclef/raw/birdclef-2024/train_audio/asbfly/XC164848.ogg')]

In [4]:
perch = bmz.list_models()["Perch"]()
perch

/storage/scratch1/7/acheung46/birdclef/.venv/lib64/python3.9/site-packages/tensorflow_hub/__init__.py:61: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import parse_version
/storage/scratch1/7/acheung46/birdclef/.venv/lib64/python3.9/site-packages/opensoundscape/ml/cnn.py:599: UserWarning:
                    This architecture is not listed in opensoundscape.ml.cnn_architectures.ARCH_DICT.
                    It will not be available for loading after saving the model with .save() (unless using pickle=True).
                    To make it re-loadable, define a function that generates the architecture from arguments: (n_classes, n_channels)
                    then use opensoundscape.ml.cnn_architectures.register_architecture() to register the generating function.

                    The function can also set the returned object's .constructor_name to the registered string key in ARCH_DICT
                    to avoid this warning and ensure it is reloaded correctly by opensoundscape.ml.load_model().

                    See opensoundscape.ml.cnn_architectures module for examples of constructor functions

  warnings.warn(
/storage/scratch1/7/acheung46/birdclef/.venv/lib64/python3.9/site-packages/opensoundscape/ml/cnn.py:623: UserWarning: Failed to detect expected # input channels of this architecture.Make sure your architecture expects the number of channels equal to `channels` argument 1). Pytorch architectures generally expect 3 channels by default.
  warnings.warn(

Perch(
  (network): MLPClassifier(
    (hidden_layers): Sequential()
    (classifier): Linear(in_features=1280, out_features=10932, bias=True)
  )
  (loss_fn): BCEWithLogitsLoss_hot()
)

In [6]:
birdnet = bmz.list_models()["BirdNET"]()
birdnet

File BirdNET_GLOBAL_6K_V2.4_Labels_af.txt already exists; skipping download.
downloading model from URL...
File BirdNET_GLOBAL_6K_V2.4_Model_FP16.tflite already exists; skipping download.

/storage/scratch1/7/acheung46/birdclef/.venv/lib64/python3.9/site-packages/opensoundscape/ml/cnn.py:599: UserWarning:
                    This architecture is not listed in opensoundscape.ml.cnn_architectures.ARCH_DICT.
                    It will not be available for loading after saving the model with .save() (unless using pickle=True).
                    To make it re-loadable, define a function that generates the architecture from arguments: (n_classes, n_channels)
                    then use opensoundscape.ml.cnn_architectures.register_architecture() to register the generating function.

                    The function can also set the returned object's .constructor_name to the registered string key in ARCH_DICT
                    to avoid this warning and ensure it is reloaded correctly by opensoundscape.ml.load_model().

                    See opensoundscape.ml.cnn_architectures module for examples of constructor functions

  warnings.warn(
/storage/scratch1/7/acheung46/birdclef/.venv/lib64/python3.9/site-packages/opensoundscape/ml/cnn.py:623: UserWarning: Failed to detect expected # input channels of this architecture.Make sure your architecture expects the number of channels equal to `channels` argument 1). Pytorch architectures generally expect 3 channels by default.
  warnings.warn(

BirdNET(
  (network): MLPClassifier(
    (hidden_layers): Sequential()
    (classifier): Linear(in_features=1024, out_features=6522, bias=True)
  )
  (loss_fn): BCEWithLogitsLoss_hot()
)

In [7]:
# NOTE: there is a warmup period for the model...
birdnet.predict(audio[0:1])
%time _ = birdnet.predict(audio)

  0%|          | 0/9 [00:00<?, ?it/s]

  0%|          | 0/14 [00:00<?, ?it/s]

CPU times: user 1.5 s, sys: 2.91 ms, total: 1.51 s
Wall time: 1.55 s

In [13]:
%time _ = birdnet.predict(audio, clip_step=1)

  0%|          | 0/38 [00:00<?, ?it/s]

CPU times: user 4.04 s, sys: 23.4 ms, total: 4.06 s
Wall time: 4.05 s

In [8]:
%time _ = birdnet.embed(audio, return_preds=False)

  0%|          | 0/14 [00:00<?, ?it/s]

CPU times: user 1.49 s, sys: 5.5 ms, total: 1.49 s
Wall time: 1.5 s

In [9]:
%time _ = birdnet.embed(audio, return_preds=False, clip_step=1)

  0%|          | 0/38 [00:00<?, ?it/s]

CPU times: user 3.99 s, sys: 24.6 ms, total: 4.01 s
Wall time: 4.03 s

In [8]:
# NOTE: there is a warmup period for the model...
perch.predict(audio[0:1])
%time _ = perch.predict(audio)

  0%|          | 0/5 [00:00<?, ?it/s]

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1750131539.825091 2836388 service.cc:146] XLA service 0x5555746a3080 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1750131539.967671 2836388 service.cc:154]   StreamExecutor device (0): Host, Default Version
2025-06-16 23:39:07.049569: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:268] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
W0000 00:00:1750131553.808833 2836388 assert_op.cc:38] Ignoring Assert operator jax2tf_infer_fn_/assert_equal_1/Assert/AssertGuard/Assert
I0000 00:00:1750131577.531276 2836388 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.

  0%|          | 0/8 [00:00<?, ?it/s]

CPU times: user 11.3 s, sys: 23 ms, total: 11.3 s
Wall time: 10.4 s

In [73]:
from birdclef.kaggle.compile import load_tflite_interpreter, run_perch_tflite
import tensorflow as tf
from contexttimer import Timer

# Path to the TFLite model
perch_tflite_path = Path("~/scratch/birdclef/models/2025/v1/Perch/torch-linear-v1/perch.tflite").expanduser()

# Load the TFLite interpreter
perch_interpreter = load_tflite_interpreter(perch_tflite_path)

# First run to warm up
perch_dataloader = perch.predict_dataloader(audio[0:1])
_ = run_perch_tflite(perch_interpreter, perch_dataloader)

# Measure execution time
def run_perch():
    perch_dataloader = perch.predict_dataloader(audio)
    return run_perch_tflite(perch_interpreter, perch_dataloader)

%time perch_out = run_perch()

2025-06-17 01:15:34.816675: E tensorflow/core/framework/node_def_util.cc:676] NodeDef mentions attribute use_inter_op_parallelism which is not in the op definition: Op<name=Transpose; signature=x:T, perm:Tperm -> y:T; attr=T:type; attr=Tperm:type,default=DT_INT32,allowed=[DT_INT32, DT_INT64]> This may be expected if your graph generating binary is newer  than this binary. Unknown attributes will be ignored. NodeDef: {{node Transpose}}

CPU times: user 846 ms, sys: 6.69 ms, total: 852 ms
Wall time: 847 ms

In [43]:
perch_out

                                                                            0     \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0      -0.042605
                                                   5.0        10.0      0.043925
                                                   10.0       15.0      0.191889
                                                   15.0       20.0      0.078761
                                                   20.0       25.0     -0.008164
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0      -0.014053
                                                   5.0        10.0      0.100804
                                                   10.0       15.0      0.064618

                                                                            1     \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0      -0.141005
                                                   5.0        10.0     -0.158573
                                                   10.0       15.0     -0.165586
                                                   15.0       20.0     -0.127910
                                                   20.0       25.0     -0.166585
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0      -0.047585
                                                   5.0        10.0     -0.103619
                                                   10.0       15.0     -0.125703

                                                                            2     \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0       0.025648
                                                   5.0        10.0      0.057496
                                                   10.0       15.0      0.032176
                                                   15.0       20.0      0.067172
                                                   20.0       25.0      0.077055
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0       0.023723
                                                   5.0        10.0      0.048283
                                                   10.0       15.0      0.040848

                                                                            3     \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0       0.041677
                                                   5.0        10.0      0.006564
                                                   10.0       15.0      0.041329
                                                   15.0       20.0     -0.001162
                                                   20.0       25.0      0.020314
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0      -0.023687
                                                   5.0        10.0     -0.017900
                                                   10.0       15.0     -0.039507

                                                                            4     \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0       0.219057
                                                   5.0        10.0      0.133760
                                                   10.0       15.0      0.241032
                                                   15.0       20.0      0.362048
                                                   20.0       25.0      0.305957
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0       0.064599
                                                   5.0        10.0     -0.002629
                                                   10.0       15.0     -0.011201

                                                                            5     \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0      -0.093321
                                                   5.0        10.0     -0.108531
                                                   10.0       15.0     -0.106465
                                                   15.0       20.0      0.020511
                                                   20.0       25.0      0.016012
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0       0.237520
                                                   5.0        10.0      0.131647
                                                   10.0       15.0      0.127931

                                                                            6     \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0      -0.045296
                                                   5.0        10.0     -0.040390
                                                   10.0       15.0     -0.038477
                                                   15.0       20.0     -0.036518
                                                   20.0       25.0     -0.023858
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0      -0.021464
                                                   5.0        10.0     -0.030436
                                                   10.0       15.0     -0.007129

                                                                            7     \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0      -0.033463
                                                   5.0        10.0     -0.005679
                                                   10.0       15.0      0.001972
                                                   15.0       20.0     -0.015141
                                                   20.0       25.0      0.043862
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0      -0.071156
                                                   5.0        10.0      0.043630
                                                   10.0       15.0      0.075738

                                                                            8     \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0       0.021493
                                                   5.0        10.0      0.057802
                                                   10.0       15.0      0.024136
                                                   15.0       20.0      0.010027
                                                   20.0       25.0      0.024226
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0       0.058777
                                                   5.0        10.0      0.004665
                                                   10.0       15.0      0.047046

                                                                            9     \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0       0.015310
                                                   5.0        10.0     -0.009464
                                                   10.0       15.0     -0.032124
                                                   15.0       20.0      0.004725
                                                   20.0       25.0      0.017723
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0       0.053190
                                                   5.0        10.0      0.058007
                                                   10.0       15.0      0.066508

                                                                        ...  \
file                                               start_time end_time  ...
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0       ...
                                                   5.0        10.0      ...
                                                   10.0       15.0      ...
                                                   15.0       20.0      ...
                                                   20.0       25.0      ...
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0       ...
                                                   5.0        10.0      ...
                                                   10.0       15.0      ...

                                                                            1270  \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0      -0.068139
                                                   5.0        10.0     -0.038134
                                                   10.0       15.0     -0.026963
                                                   15.0       20.0     -0.066474
                                                   20.0       25.0     -0.001365
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0       0.035056
                                                   5.0        10.0      0.015901
                                                   10.0       15.0     -0.079636

                                                                            1271  \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0       0.003904
                                                   5.0        10.0      0.008686
                                                   10.0       15.0      0.026634
                                                   15.0       20.0      0.027452
                                                   20.0       25.0      0.037094
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0       0.012955
                                                   5.0        10.0      0.050458
                                                   10.0       15.0      0.020278

                                                                            1272  \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0       0.050975
                                                   5.0        10.0      0.029846
                                                   10.0       15.0      0.156389
                                                   15.0       20.0      0.094284
                                                   20.0       25.0      0.116067
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0       0.021173
                                                   5.0        10.0     -0.033126
                                                   10.0       15.0     -0.010663

                                                                            1273  \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0       0.275301
                                                   5.0        10.0      0.264155
                                                   10.0       15.0      0.152691
                                                   15.0       20.0      0.213098
                                                   20.0       25.0      0.258913
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0       0.084607
                                                   5.0        10.0     -0.049295
                                                   10.0       15.0     -0.075536

                                                                            1274  \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0      -0.033074
                                                   5.0        10.0     -0.039377
                                                   10.0       15.0     -0.041970
                                                   15.0       20.0     -0.039534
                                                   20.0       25.0     -0.025404
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0       0.076791
                                                   5.0        10.0      0.018714
                                                   10.0       15.0      0.019117

                                                                            1275  \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0       0.031940
                                                   5.0        10.0      0.053930
                                                   10.0       15.0      0.035128
                                                   15.0       20.0      0.042525
                                                   20.0       25.0     -0.001547
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0       0.011343
                                                   5.0        10.0      0.047943
                                                   10.0       15.0      0.044853

                                                                            1276  \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0       0.258302
                                                   5.0        10.0      0.253043
                                                   10.0       15.0      0.188365
                                                   15.0       20.0      0.188616
                                                   20.0       25.0      0.097353
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0       0.169738
                                                   5.0        10.0      0.053109
                                                   10.0       15.0      0.070455

                                                                            1277  \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0       0.064362
                                                   5.0        10.0      0.125121
                                                   10.0       15.0      0.136109
                                                   15.0       20.0      0.044475
                                                   20.0       25.0      0.008992
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0       0.019080
                                                   5.0        10.0      0.016290
                                                   10.0       15.0      0.013334

                                                                            1278  \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0       0.141944
                                                   5.0        10.0      0.033679
                                                   10.0       15.0      0.064860
                                                   15.0       20.0     -0.044708
                                                   20.0       25.0      0.075674
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0       0.053530
                                                   5.0        10.0     -0.004038
                                                   10.0       15.0      0.015902

                                                                            1279
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0      -0.002607
                                                   5.0        10.0     -0.040570
                                                   10.0       15.0      0.021250
                                                   15.0       20.0      0.046647
                                                   20.0       25.0     -0.023289
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        5.0      -0.014084
                                                   5.0        10.0      0.003749
                                                   10.0       15.0     -0.014509

[8 rows x 1280 columns]

In [40]:
perch_out.shape

(8, 1280)

In [10]:
perch_interpreter.get_input_details()

[{'name': 'serving_default_inputs:0',
  'index': 0,
  'shape': array([     1, 160000], dtype=int32),
  'shape_signature': array([    -1, 160000], dtype=int32),
  'dtype': numpy.float32,
  'quantization': (0.0, 0),
  'quantization_parameters': {'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32),
   'quantized_dimension': 0},
  'sparsity_parameters': {}}]

In [11]:
perch_interpreter.get_output_details()

[{'name': 'StatefulPartitionedCall:2',
  'index': 384,
  'shape': array([  1, 500, 160], dtype=int32),
  'shape_signature': array([ -1, 500, 160], dtype=int32),
  'dtype': numpy.float32,
  'quantization': (0.0, 0),
  'quantization_parameters': {'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32),
   'quantized_dimension': 0},
  'sparsity_parameters': {}},
 {'name': 'StatefulPartitionedCall:0',
  'index': 828,
  'shape': array([   1, 1280], dtype=int32),
  'shape_signature': array([  -1, 1280], dtype=int32),
  'dtype': numpy.float32,
  'quantization': (0.0, 0),
  'quantization_parameters': {'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32),
   'quantized_dimension': 0},
  'sparsity_parameters': {}},
 {'name': 'StatefulPartitionedCall:3',
  'index': 832,
  'shape': array([   1, 2333], dtype=int32),
  'shape_signature': array([  -1, 2333], dtype=int32),
  'dtype': numpy.float32,
  'quantization': (0.0, 0),
  'quantization_parameters': {'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32),
   'quantized_dimension': 0},
  'sparsity_parameters': {}},
 {'name': 'StatefulPartitionedCall:5',
  'index': 836,
  'shape': array([ 1, 41], dtype=int32),
  'shape_signature': array([-1, 41], dtype=int32),
  'dtype': numpy.float32,
  'quantization': (0.0, 0),
  'quantization_parameters': {'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32),
   'quantized_dimension': 0},
  'sparsity_parameters': {}},
 {'name': 'StatefulPartitionedCall:1',
  'index': 834,
  'shape': array([  1, 249], dtype=int32),
  'shape_signature': array([ -1, 249], dtype=int32),
  'dtype': numpy.float32,
  'quantization': (0.0, 0),
  'quantization_parameters': {'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32),
   'quantized_dimension': 0},
  'sparsity_parameters': {}},
 {'name': 'StatefulPartitionedCall:4',
  'index': 830,
  'shape': array([    1, 10932], dtype=int32),
  'shape_signature': array([   -1, 10932], dtype=int32),
  'dtype': numpy.float32,
  'quantization': (0.0, 0),
  'quantization_parameters': {'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32),
   'quantized_dimension': 0},
  'sparsity_parameters': {}}]

In [31]:
from birdclef.kaggle.compile import load_tflite_interpreter
import tensorflow as tf
from contexttimer import Timer

# Path to the TFLite model
birdnet_tflite_path = Path("~/scratch/birdclef/models/2025/v1/BirdNET/torch-linear-v1/birdnet.tflite").expanduser()

# Load the TFLite interpreter
birdnet_interpreter = load_tflite_interpreter(birdnet_tflite_path)

In [33]:
birdnet_input_details = birdnet_interpreter.get_input_details()
birdnet_output_details = birdnet_interpreter.get_output_details()

In [14]:
birdnet_input_details

[{'name': 'INPUT',
  'index': 0,
  'shape': array([     1, 144000], dtype=int32),
  'shape_signature': array([    -1, 144000], dtype=int32),
  'dtype': numpy.float32,
  'quantization': (0.0, 0),
  'quantization_parameters': {'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32),
   'quantized_dimension': 0},
  'sparsity_parameters': {}}]

In [15]:
birdnet_output_details

[{'name': 'Identity',
  'index': 546,
  'shape': array([   1, 6522], dtype=int32),
  'shape_signature': array([  -1, 6522], dtype=int32),
  'dtype': numpy.float32,
  'quantization': (0.0, 0),
  'quantization_parameters': {'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32),
   'quantized_dimension': 0},
  'sparsity_parameters': {}}]

In [34]:
birdnet_dataloader = birdnet.predict_dataloader(audio, clip_step=1)

res = []
for batch in birdnet_dataloader:
    birdnet_interpreter.set_tensor(birdnet_input_details[0]['index'], batch[0])
    birdnet_interpreter.invoke()
    output_data = birdnet_interpreter.get_tensor(birdnet_output_details[0]['index'])
    res.append(output_data)

res[0].shape

(1, 6522)

In [ ]:
birdnet_interpreter = load_tflite_interpreter(birdnet_tflite_path)
# birdnet_interpreter.allocate_tensors()

birdnet_dataloader = birdnet.predict_dataloader(audio, clip_step=1)

res = []
for batch in birdnet_dataloader:
    birdnet_input_details = birdnet_interpreter.get_input_details()[0]
    input_layer_idx = birdnet_input_details['index']
    birdnet_output_details = birdnet_interpreter.get_output_details()[0]
    embedding_idx = birdnet_output_details['index'] - 1
    
    batch = batch[0]
    birdnet_interpreter.resize_tensor_input(
        input_layer_idx,
        [len(batch), *batch[0].shape]
    )
    birdnet_interpreter.allocate_tensors()
    birdnet_interpreter.set_tensor(input_layer_idx, np.array(batch, dtype=np.float32))
    birdnet_interpreter.invoke()
    output_data = birdnet_interpreter.get_tensor(embedding_idx)
    
    res.append(output_data)
res[0].shape

(1, 1024)

In [69]:
import numpy as np
import pandas as pd

birdnet_out_df = pd.DataFrame(
    data=np.stack(res).squeeze(),
    index=birdnet_dataloader.dataset.dataset.label_df.index,
)
birdnet_out_df

                                                                            0     \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        3.0       0.000000
                                                   1.0        4.0       0.000000
                                                   2.0        5.0       0.334714
                                                   3.0        6.0       0.079557
                                                   4.0        7.0       0.000000
                                                   5.0        8.0       0.000000
                                                   6.0        9.0       0.000000
                                                   7.0        10.0      0.083778
                                                   8.0        11.0      0.000000
                                                   9.0        12.0      0.000000
                                                   10.0       13.0      0.000000
                                                   11.0       14.0      0.000000
                                                   12.0       15.0      0.036325
                                                   13.0       16.0      0.000000
                                                   14.0       17.0      0.000000
                                                   15.0       18.0      0.000000
                                                   16.0       19.0      0.056075
                                                   17.0       20.0      0.000000
                                                   18.0       21.0      0.007163
                                                   19.0       22.0      0.000000
                                                   20.0       23.0      0.000000
                                                   21.0       24.0      0.226059
                                                   22.0       25.0      0.110504
                                                   23.0       26.0      0.000000
                                                   24.0       27.0      0.000000
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        3.0       0.047440
                                                   1.0        4.0       0.281672
                                                   2.0        5.0       0.025264
                                                   3.0        6.0       0.090743
                                                   4.0        7.0       0.131011
                                                   5.0        8.0       0.000000
                                                   6.0        9.0       0.000000
                                                   7.0        10.0      0.000000
                                                   8.0        11.0      0.000000
                                                   9.0        12.0      0.000000
                                                   10.0       13.0      0.000000
                                                   11.0       14.0      0.000000
                                                   12.0       15.0      0.000000

                                                                            1     \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        3.0       1.776116
                                                   1.0        4.0       2.351565
                                                   2.0        5.0       2.474020
                                                   3.0        6.0       2.158225
                                                   4.0        7.0       2.082779
                                                   5.0        8.0       2.529492
                                                   6.0        9.0       2.463259
                                                   7.0        10.0      1.343889
                                                   8.0        11.0      2.688185
                                                   9.0        12.0      2.595195
                                                   10.0       13.0      2.830796
                                                   11.0       14.0      2.577329
                                                   12.0       15.0      1.932714
                                                   13.0       16.0      2.742001
                                                   14.0       17.0      2.794627
                                                   15.0       18.0      2.760626
                                                   16.0       19.0      1.218354
                                                   17.0       20.0      1.246212
                                                   18.0       21.0      2.464102
                                                   19.0       22.0      2.772048
                                                   20.0       23.0      2.726243
                                                   21.0       24.0      1.835046
                                                   22.0       25.0      2.743175
                                                   23.0       26.0      2.680466
                                                   24.0       27.0      2.141247
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        3.0       0.000000
                                                   1.0        4.0       0.225586
                                                   2.0        5.0       0.000000
                                                   3.0        6.0       0.000000
                                                   4.0        7.0       0.005072
                                                   5.0        8.0       0.196379
                                                   6.0        9.0       0.000000
                                                   7.0        10.0      0.000000
                                                   8.0        11.0      0.111389
                                                   9.0        12.0      0.495703
                                                   10.0       13.0      0.155074
                                                   11.0       14.0      0.074548
                                                   12.0       15.0      0.138546

                                                                            2     \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        3.0       1.586924
                                                   1.0        4.0       1.668995
                                                   2.0        5.0       1.460096
                                                   3.0        6.0       0.970361
                                                   4.0        7.0       1.094857
                                                   5.0        8.0       0.862146
                                                   6.0        9.0       1.195987
                                                   7.0        10.0      0.678529
                                                   8.0        11.0      0.963253
                                                   9.0        12.0      1.449738
                                                   10.0       13.0      1.543396
                                                   11.0       14.0      1.475815
                                                   12.0       15.0      0.257240
                                                   13.0       16.0      1.133828
                                                   14.0       17.0      1.045240
                                                   15.0       18.0      1.240978
                                                   16.0       19.0      0.274411
                                                   17.0       20.0      0.912371
                                                   18.0       21.0      0.930893
                                                   19.0       22.0      1.405342
                                                   20.0       23.0      1.555661
                                                   21.0       24.0      0.728920
                                                   22.0       25.0      1.194592
                                                   23.0       26.0      1.589856
                                                   24.0       27.0      1.136018
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        3.0       0.590542
                                                   1.0        4.0       0.000000
                                                   2.0        5.0       0.388307
                                                   3.0        6.0       0.091449
                                                   4.0        7.0       0.625671
                                                   5.0        8.0       0.672768
                                                   6.0        9.0       0.831262
                                                   7.0        10.0      0.298642
                                                   8.0        11.0      0.375447
                                                   9.0        12.0      0.976500
                                                   10.0       13.0      0.670251
                                                   11.0       14.0      0.785869
                                                   12.0       15.0      0.398364

                                                                            3     \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        3.0       0.000000
                                                   1.0        4.0       0.000000
                                                   2.0        5.0       0.000000
                                                   3.0        6.0       0.000000
                                                   4.0        7.0       0.000000
                                                   5.0        8.0       0.000000
                                                   6.0        9.0       0.000000
                                                   7.0        10.0      0.007887
                                                   8.0        11.0      0.000000
                                                   9.0        12.0      0.000000
                                                   10.0       13.0      0.000000
                                                   11.0       14.0      0.000000
                                                   12.0       15.0      0.000000
                                                   13.0       16.0      0.000000
                                                   14.0       17.0      0.012030
                                                   15.0       18.0      0.000000
                                                   16.0       19.0      0.072336
                                                   17.0       20.0      0.206694
                                                   18.0       21.0      0.000000
                                                   19.0       22.0      0.018764
                                                   20.0       23.0      0.078587
                                                   21.0       24.0      0.283710
                                                   22.0       25.0      0.099252
                                                   23.0       26.0      0.000000
                                                   24.0       27.0      0.025845
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        3.0       0.000000
                                                   1.0        4.0       0.229494
                                                   2.0        5.0       0.205726
                                                   3.0        6.0       0.322108
                                                   4.0        7.0       0.346739
                                                   5.0        8.0       0.569694
                                                   6.0        9.0       1.201391
                                                   7.0        10.0      0.594629
                                                   8.0        11.0      0.406568
                                                   9.0        12.0      0.275502
                                                   10.0       13.0      0.073664
                                                   11.0       14.0      1.177096
                                                   12.0       15.0      1.253645

                                                                            4     \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        3.0       0.756652
                                                   1.0        4.0       0.869696
                                                   2.0        5.0       0.876815
                                                   3.0        6.0       1.015812
                                                   4.0        7.0       0.778769
                                                   5.0        8.0       1.080615
                                                   6.0        9.0       0.990851
                                                   7.0        10.0      0.497621
                                                   8.0        11.0      0.910058
                                                   9.0        12.0      1.189442
                                                   10.0       13.0      1.252853
                                                   11.0       14.0      0.942755
                                                   12.0       15.0      0.715133
                                                   13.0       16.0      1.255280
                                                   14.0       17.0      1.137546
                                                   15.0       18.0      1.230393
                                                   16.0       19.0      1.097591
                                                   17.0       20.0      0.885612
                                                   18.0       21.0      1.171979
                                                   19.0       22.0      0.993530
                                                   20.0       23.0      0.997795
                                                   21.0       24.0      0.159600
                                                   22.0       25.0      0.382807
                                                   23.0       26.0      1.299209
                                                   24.0       27.0      1.466934
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        3.0       1.134791
                                                   1.0        4.0       0.783373
                                                   2.0        5.0       0.891993
                                                   3.0        6.0       0.643962
                                                   4.0        7.0       0.224733
                                                   5.0        8.0       0.544175
                                                   6.0        9.0       0.838430
                                                   7.0        10.0      1.064369
                                                   8.0        11.0      0.650372
                                                   9.0        12.0      0.941751
                                                   10.0       13.0      1.000551
                                                   11.0       14.0      0.548249
                                                   12.0       15.0      0.335548

                                                                            5     \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        3.0       0.339030
                                                   1.0        4.0       0.481594
                                                   2.0        5.0       0.453922
                                                   3.0        6.0       0.547688
                                                   4.0        7.0       0.349799
                                                   5.0        8.0       0.756443
                                                   6.0        9.0       0.550856
                                                   7.0        10.0      0.370414
                                                   8.0        11.0      0.794969
                                                   9.0        12.0      0.254227
                                                   10.0       13.0      0.542328
                                                   11.0       14.0      0.278049
                                                   12.0       15.0      0.346976
                                                   13.0       16.0      0.205889
                                                   14.0       17.0      0.139147
                                                   15.0       18.0      0.106181
                                                   16.0       19.0      0.136450
                                                   17.0       20.0      0.040604
                                                   18.0       21.0      0.843106
                                                   19.0       22.0      0.639892
                                                   20.0       23.0      0.944403
                                                   21.0       24.0      0.546391
                                                   22.0       25.0      0.134943
                                                   23.0       26.0      0.595738
                                                   24.0       27.0      0.545831
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        3.0       0.582356
                                                   1.0        4.0       0.642748
                                                   2.0        5.0       0.471162
                                                   3.0        6.0       0.000000
                                                   4.0        7.0       0.368564
                                                   5.0        8.0       0.398793
                                                   6.0        9.0       0.226563
                                                   7.0        10.0      0.121955
                                                   8.0        11.0      0.093171
                                                   9.0        12.0      0.224734
                                                   10.0       13.0      0.647160
                                                   11.0       14.0      0.025984
                                                   12.0       15.0      0.128232

                                                                            6     \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        3.0       0.013997
                                                   1.0        4.0       0.131164
                                                   2.0        5.0       0.000000
                                                   3.0        6.0       0.341653
                                                   4.0        7.0       0.144341

In [65]:
bmz_birdnet_out = birdnet.embed(audio, clip_step=1)
print(bmz_birdnet_out.shape)
pd.DataFrame(
    data=bmz_birdnet_out.to_numpy(),
    index=birdnet_dataloader.dataset.dataset.label_df.index,
)

  0%|          | 0/38 [00:00<?, ?it/s]

(38, 1024)

                                                                            0     \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        3.0       0.000000
                                                   1.0        4.0       0.000000
                                                   2.0        5.0       0.334715
                                                   3.0        6.0       0.079556
                                                   4.0        7.0       0.000000
                                                   5.0        8.0       0.000000
                                                   6.0        9.0       0.000000
                                                   7.0        10.0      0.083778
                                                   8.0        11.0      0.000000
                                                   9.0        12.0      0.000000
                                                   10.0       13.0      0.000000
                                                   11.0       14.0      0.000000
                                                   12.0       15.0      0.036325
                                                   13.0       16.0      0.000000
                                                   14.0       17.0      0.000000
                                                   15.0       18.0      0.000000
                                                   16.0       19.0      0.056075
                                                   17.0       20.0      0.000000
                                                   18.0       21.0      0.007163
                                                   19.0       22.0      0.000000
                                                   20.0       23.0      0.000000
                                                   21.0       24.0      0.226059
                                                   22.0       25.0      0.110503
                                                   23.0       26.0      0.000000
                                                   24.0       27.0      0.000000
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        3.0       0.047439
                                                   1.0        4.0       0.281672
                                                   2.0        5.0       0.025264
                                                   3.0        6.0       0.090742
                                                   4.0        7.0       0.131011
                                                   5.0        8.0       0.000000
                                                   6.0        9.0       0.000000
                                                   7.0        10.0      0.000000
                                                   8.0        11.0      0.000000
                                                   9.0        12.0      0.000000
                                                   10.0       13.0      0.000000
                                                   11.0       14.0      0.000000
                                                   12.0       15.0      0.000000

                                                                            1     \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        3.0       1.776114
                                                   1.0        4.0       2.351564
                                                   2.0        5.0       2.474020
                                                   3.0        6.0       2.158225
                                                   4.0        7.0       2.082778
                                                   5.0        8.0       2.529491
                                                   6.0        9.0       2.463259
                                                   7.0        10.0      1.343888
                                                   8.0        11.0      2.688186
                                                   9.0        12.0      2.595194
                                                   10.0       13.0      2.830796
                                                   11.0       14.0      2.577329
                                                   12.0       15.0      1.932714
                                                   13.0       16.0      2.742002
                                                   14.0       17.0      2.794627
                                                   15.0       18.0      2.760627
                                                   16.0       19.0      1.218353
                                                   17.0       20.0      1.246211
                                                   18.0       21.0      2.464102
                                                   19.0       22.0      2.772046
                                                   20.0       23.0      2.726244
                                                   21.0       24.0      1.835047
                                                   22.0       25.0      2.743175
                                                   23.0       26.0      2.680466
                                                   24.0       27.0      2.141247
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        3.0       0.000000
                                                   1.0        4.0       0.225587
                                                   2.0        5.0       0.000000
                                                   3.0        6.0       0.000000
                                                   4.0        7.0       0.005074
                                                   5.0        8.0       0.196378
                                                   6.0        9.0       0.000000
                                                   7.0        10.0      0.000000
                                                   8.0        11.0      0.111390
                                                   9.0        12.0      0.495702
                                                   10.0       13.0      0.155075
                                                   11.0       14.0      0.074548
                                                   12.0       15.0      0.138545

                                                                            2     \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        3.0       1.586925
                                                   1.0        4.0       1.668995
                                                   2.0        5.0       1.460097
                                                   3.0        6.0       0.970363
                                                   4.0        7.0       1.094858
                                                   5.0        8.0       0.862148
                                                   6.0        9.0       1.195989
                                                   7.0        10.0      0.678530
                                                   8.0        11.0      0.963252
                                                   9.0        12.0      1.449739
                                                   10.0       13.0      1.543396
                                                   11.0       14.0      1.475815
                                                   12.0       15.0      0.257241
                                                   13.0       16.0      1.133830
                                                   14.0       17.0      1.045240
                                                   15.0       18.0      1.240978
                                                   16.0       19.0      0.274410
                                                   17.0       20.0      0.912369
                                                   18.0       21.0      0.930895
                                                   19.0       22.0      1.405342
                                                   20.0       23.0      1.555661
                                                   21.0       24.0      0.728921
                                                   22.0       25.0      1.194592
                                                   23.0       26.0      1.589856
                                                   24.0       27.0      1.136019
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        3.0       0.590541
                                                   1.0        4.0       0.000000
                                                   2.0        5.0       0.388307
                                                   3.0        6.0       0.091448
                                                   4.0        7.0       0.625671
                                                   5.0        8.0       0.672767
                                                   6.0        9.0       0.831262
                                                   7.0        10.0      0.298643
                                                   8.0        11.0      0.375447
                                                   9.0        12.0      0.976499
                                                   10.0       13.0      0.670250
                                                   11.0       14.0      0.785869
                                                   12.0       15.0      0.398363

                                                                            3     \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        3.0       0.000000
                                                   1.0        4.0       0.000000
                                                   2.0        5.0       0.000000
                                                   3.0        6.0       0.000000
                                                   4.0        7.0       0.000000
                                                   5.0        8.0       0.000000
                                                   6.0        9.0       0.000000
                                                   7.0        10.0      0.007888
                                                   8.0        11.0      0.000000
                                                   9.0        12.0      0.000000
                                                   10.0       13.0      0.000000
                                                   11.0       14.0      0.000000
                                                   12.0       15.0      0.000000
                                                   13.0       16.0      0.000000
                                                   14.0       17.0      0.012030
                                                   15.0       18.0      0.000000
                                                   16.0       19.0      0.072336
                                                   17.0       20.0      0.206695
                                                   18.0       21.0      0.000000
                                                   19.0       22.0      0.018765
                                                   20.0       23.0      0.078587
                                                   21.0       24.0      0.283710
                                                   22.0       25.0      0.099252
                                                   23.0       26.0      0.000000
                                                   24.0       27.0      0.025845
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        3.0       0.000000
                                                   1.0        4.0       0.229494
                                                   2.0        5.0       0.205726
                                                   3.0        6.0       0.322108
                                                   4.0        7.0       0.346740
                                                   5.0        8.0       0.569694
                                                   6.0        9.0       1.201391
                                                   7.0        10.0      0.594628
                                                   8.0        11.0      0.406568
                                                   9.0        12.0      0.275502
                                                   10.0       13.0      0.073664
                                                   11.0       14.0      1.177096
                                                   12.0       15.0      1.253644

                                                                            4     \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        3.0       0.756653
                                                   1.0        4.0       0.869696
                                                   2.0        5.0       0.876816
                                                   3.0        6.0       1.015812
                                                   4.0        7.0       0.778769
                                                   5.0        8.0       1.080616
                                                   6.0        9.0       0.990852
                                                   7.0        10.0      0.497622
                                                   8.0        11.0      0.910059
                                                   9.0        12.0      1.189442
                                                   10.0       13.0      1.252854
                                                   11.0       14.0      0.942755
                                                   12.0       15.0      0.715134
                                                   13.0       16.0      1.255279
                                                   14.0       17.0      1.137547
                                                   15.0       18.0      1.230393
                                                   16.0       19.0      1.097591
                                                   17.0       20.0      0.885611
                                                   18.0       21.0      1.171979
                                                   19.0       22.0      0.993532
                                                   20.0       23.0      0.997797
                                                   21.0       24.0      0.159600
                                                   22.0       25.0      0.382807
                                                   23.0       26.0      1.299209
                                                   24.0       27.0      1.466933
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        3.0       1.134792
                                                   1.0        4.0       0.783372
                                                   2.0        5.0       0.891994
                                                   3.0        6.0       0.643962
                                                   4.0        7.0       0.224732
                                                   5.0        8.0       0.544174
                                                   6.0        9.0       0.838430
                                                   7.0        10.0      1.064370
                                                   8.0        11.0      0.650371
                                                   9.0        12.0      0.941750
                                                   10.0       13.0      1.000549
                                                   11.0       14.0      0.548250
                                                   12.0       15.0      0.335547

                                                                            5     \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        3.0       0.339029
                                                   1.0        4.0       0.481593
                                                   2.0        5.0       0.453921
                                                   3.0        6.0       0.547687
                                                   4.0        7.0       0.349799
                                                   5.0        8.0       0.756442
                                                   6.0        9.0       0.550856
                                                   7.0        10.0      0.370414
                                                   8.0        11.0      0.794968
                                                   9.0        12.0      0.254227
                                                   10.0       13.0      0.542327
                                                   11.0       14.0      0.278048
                                                   12.0       15.0      0.346975
                                                   13.0       16.0      0.205888
                                                   14.0       17.0      0.139148
                                                   15.0       18.0      0.106180
                                                   16.0       19.0      0.136450
                                                   17.0       20.0      0.040604
                                                   18.0       21.0      0.843105
                                                   19.0       22.0      0.639893
                                                   20.0       23.0      0.944403
                                                   21.0       24.0      0.546392
                                                   22.0       25.0      0.134944
                                                   23.0       26.0      0.595738
                                                   24.0       27.0      0.545831
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        3.0       0.582356
                                                   1.0        4.0       0.642748
                                                   2.0        5.0       0.471163
                                                   3.0        6.0       0.000000
                                                   4.0        7.0       0.368564
                                                   5.0        8.0       0.398793
                                                   6.0        9.0       0.226564
                                                   7.0        10.0      0.121955
                                                   8.0        11.0      0.093171
                                                   9.0        12.0      0.224735
                                                   10.0       13.0      0.647161
                                                   11.0       14.0      0.025984
                                                   12.0       15.0      0.128233

                                                                            6     \
file                                               start_time end_time
/storage/home/hcoda1/7/acheung46/scratch/birdcl... 0.0        3.0       0.013997
                                                   1.0        4.0       0.131164
                                                   2.0        5.0       0.000000
                                                   3.0        6.0       0.341652
                                                   4.0        7.0       0.144341

In [66]:
from birdclef.kaggle.compile import run_birdnet_tflite

# birdnet_dataloader = birdnet.predict_dataloader(audio[0:1])
# _ = run_birdnet_tflite(birdnet_interpreter, birdnet_dataloader)

def run_birdnet(interpreter, clip_step=None):
    birdnet_dataloader = birdnet.predict_dataloader(audio, clip_step=clip_step)
    return run_birdnet_tflite(interpreter, birdnet_dataloader)

%time _ = run_birdnet(birdnet_interpreter)
%time _ = run_birdnet(birdnet_interpreter, clip_step=1)

CPU times: user 1.26 s, sys: 8.78 ms, total: 1.27 s
Wall time: 1.28 s
CPU times: user 3.39 s, sys: 33.8 ms, total: 3.42 s
Wall time: 3.46 s

In [67]:
birdnet_interpreter_multi = load_tflite_interpreter(birdnet_tflite_path, num_threads=8)

%time _ = run_birdnet(birdnet_interpreter_multi)
%time _ = run_birdnet(birdnet_interpreter_multi, clip_step=1)

CPU times: user 1.84 s, sys: 381 ms, total: 2.23 s
Wall time: 1.7 s
CPU times: user 4.21 s, sys: 162 ms, total: 4.37 s
Wall time: 2.59 s

### Without experimental_preserve_all_tensors

In [139]:
from birdclef.kaggle.compile import run_birdnet_tflite

def _load_tflite_interpreter(model_path: Path, num_threads: int = None):
    """Load a TFLite interpreter for the given model path."""
    interpreter = tf.lite.Interpreter(
        num_threads=num_threads,
        model_path=Path(model_path).expanduser().as_posix(),
    )
    interpreter.allocate_tensors()
    return interpreter

def _run_birdnet_tflite(interpreter, dataloader) -> pd.DataFrame:
    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()
    res = []
    for batch in dataloader:
        interpreter.set_tensor(input_details[0]["index"], batch[0])
        interpreter.invoke()
        output_data = interpreter.get_tensor(output_details[0]["index"])
        res.append(output_data)
    return pd.DataFrame(
        data=np.stack(res).squeeze(),
        index=dataloader.dataset.dataset.label_df.index,
    )

def _run_birdnet(interpreter, clip_step=None):
    birdnet_dataloader = birdnet.predict_dataloader(audio, clip_step=clip_step)
    return _run_birdnet_tflite(interpreter, birdnet_dataloader)

In [140]:
birdnet_interpreter_no_preserve = _load_tflite_interpreter(birdnet_tflite_path, num_threads=8)

%time _ = _run_birdnet(birdnet_interpreter_no_preserve)
%time _ = _run_birdnet(birdnet_interpreter_no_preserve, clip_step=1)

CPU times: user 1.11 s, sys: 47.8 ms, total: 1.15 s
Wall time: 679 ms
CPU times: user 3.81 s, sys: 33.8 ms, total: 3.84 s
Wall time: 1.87 s

In [141]:
birdnet_interpreter_no_preserve_multi = _load_tflite_interpreter(birdnet_tflite_path, num_threads=8)

%time _ = _run_birdnet(birdnet_interpreter_no_preserve_multi)
%time _ = _run_birdnet(birdnet_interpreter_no_preserve_multi, clip_step=1)

CPU times: user 1.91 s, sys: 19.6 ms, total: 1.93 s
Wall time: 790 ms
CPU times: user 4.14 s, sys: 36.1 ms, total: 4.18 s
Wall time: 1.9 s

In [134]:
from pathlib import Path
import json
from birdclef.config import model_config
from birdclef.torch.model import LinearClassifier

model_path = Path("~/scratch/birdclef/models/2025/v1/BirdNET/torch-linear-v1/").expanduser()

label_to_index = json.loads((model_path / "label_to_idx.json").read_text())
checkpoint = list(model_path.glob("checkpoints/*.ckpt"))[0]
classifier = LinearClassifier.load_from_checkpoint(
    checkpoint.as_posix(),
    input_dim=model_config["BirdNET"]["embed_size"],
    num_classes=len(label_to_index),
)
classifier.eval()

LinearClassifier(
  (model): Sequential(
    (0): Linear(in_features=1024, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=205, bias=True)
  )
  (loss_fn): CrossEntropyLoss()
)

In [135]:
import polars as pl
import torch

# convert the column "file" to a string
df = birdnet_out_df.reset_index()
df["file"] = df["file"].astype(str)
df = pl.from_pandas(df)
df.head()

shape: (5, 1_027)
┌───────────────┬────────────┬──────────┬──────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ file          ┆ start_time ┆ end_time ┆ 0        ┆ … ┆ 1020     ┆ 1021     ┆ 1022     ┆ 1023     │
│ ---           ┆ ---        ┆ ---      ┆ ---      ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ str           ┆ f64        ┆ f64      ┆ f32      ┆   ┆ f32      ┆ f32      ┆ f32      ┆ f32      │
╞═══════════════╪════════════╪══════════╪══════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ /storage/home ┆ 0.0        ┆ 3.0      ┆ 0.0      ┆ … ┆ 1.088349 ┆ 0.308457 ┆ 0.792822 ┆ 1.315303 │
│ /hcoda1/7/ach ┆            ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ eung…         ┆            ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ /storage/home ┆ 1.0        ┆ 4.0      ┆ 0.0      ┆ … ┆ 1.272554 ┆ 0.420784 ┆ 1.083935 ┆ 1.059069 │
│ /hcoda1/7/ach ┆            ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ eung…         ┆            ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ /storage/home ┆ 2.0        ┆ 5.0      ┆ 0.334714 ┆ … ┆ 1.219458 ┆ 0.210007 ┆ 1.754441 ┆ 0.529761 │
│ /hcoda1/7/ach ┆            ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ eung…         ┆            ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ /storage/home ┆ 3.0        ┆ 6.0      ┆ 0.079557 ┆ … ┆ 1.940921 ┆ 0.761787 ┆ 0.853025 ┆ 0.0      │
│ /hcoda1/7/ach ┆            ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ eung…         ┆            ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ /storage/home ┆ 4.0        ┆ 7.0      ┆ 0.0      ┆ … ┆ 1.497738 ┆ 0.214118 ┆ 0.992445 ┆ 1.318701 │
│ /hcoda1/7/ach ┆            ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ eung…         ┆            ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
└───────────────┴────────────┴──────────┴──────────┴───┴──────────┴──────────┴──────────┴──────────┘

In [136]:
interval_length = 5
df = df.with_columns(
    ((pl.col("start_time") + pl.col("end_time")) / 2 / interval_length)
    .cast(pl.Int64)
    .alias("interval")
)
df.head()

shape: (5, 1_028)
┌───────────────┬────────────┬──────────┬──────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ file          ┆ start_time ┆ end_time ┆ 0        ┆ … ┆ 1021     ┆ 1022     ┆ 1023     ┆ interval │
│ ---           ┆ ---        ┆ ---      ┆ ---      ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ str           ┆ f64        ┆ f64      ┆ f32      ┆   ┆ f32      ┆ f32      ┆ f32      ┆ i64      │
╞═══════════════╪════════════╪══════════╪══════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ /storage/home ┆ 0.0        ┆ 3.0      ┆ 0.0      ┆ … ┆ 0.308457 ┆ 0.792822 ┆ 1.315303 ┆ 0        │
│ /hcoda1/7/ach ┆            ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ eung…         ┆            ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ /storage/home ┆ 1.0        ┆ 4.0      ┆ 0.0      ┆ … ┆ 0.420784 ┆ 1.083935 ┆ 1.059069 ┆ 0        │
│ /hcoda1/7/ach ┆            ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ eung…         ┆            ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ /storage/home ┆ 2.0        ┆ 5.0      ┆ 0.334714 ┆ … ┆ 0.210007 ┆ 1.754441 ┆ 0.529761 ┆ 0        │
│ /hcoda1/7/ach ┆            ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ eung…         ┆            ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ /storage/home ┆ 3.0        ┆ 6.0      ┆ 0.079557 ┆ … ┆ 0.761787 ┆ 0.853025 ┆ 0.0      ┆ 0        │
│ /hcoda1/7/ach ┆            ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ eung…         ┆            ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ /storage/home ┆ 4.0        ┆ 7.0      ┆ 0.0      ┆ … ┆ 0.214118 ┆ 0.992445 ┆ 1.318701 ┆ 1        │
│ /hcoda1/7/ach ┆            ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ eung…         ┆            ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
└───────────────┴────────────┴──────────┴──────────┴───┴──────────┴──────────┴──────────┴──────────┘

In [137]:
df = df.group_by(
    ["file", "interval"]
).agg(
    pl.col("*").exclude(["file", "interval", "start_time", "end_time"]).mean()
)
df = df.with_columns(
    pl.col("interval")
    .add(1)
    .mul(interval_length)
    .alias("end_time")
).drop("interval")
df.head()

shape: (5, 1_026)
┌─────────────────┬──────────┬──────────┬──────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ file            ┆ 0        ┆ 1        ┆ 2        ┆ … ┆ 1021     ┆ 1022     ┆ 1023     ┆ end_time │
│ ---             ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ str             ┆ f32      ┆ f32      ┆ f32      ┆   ┆ f32      ┆ f32      ┆ f32      ┆ i64      │
╞═════════════════╪══════════╪══════════╪══════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ /storage/home/h ┆ 0.067312 ┆ 2.551396 ┆ 1.294874 ┆ … ┆ 0.607609 ┆ 0.863365 ┆ 0.513562 ┆ 25       │
│ coda1/7/acheung ┆          ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ …               ┆          ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ /storage/home/h ┆ 0.103568 ┆ 2.189981 ┆ 1.421594 ┆ … ┆ 0.425258 ┆ 1.121056 ┆ 0.726033 ┆ 5        │
│ coda1/7/acheung ┆          ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ …               ┆          ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ /storage/home/h ┆ 0.016756 ┆ 2.221521 ┆ 0.958955 ┆ … ┆ 0.492773 ┆ 0.81705  ┆ 1.022706 ┆ 10       │
│ coda1/7/acheung ┆          ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ …               ┆          ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ /storage/home/h ┆ 0.11128  ┆ 0.056397 ┆ 0.267574 ┆ … ┆ 0.276193 ┆ 0.235538 ┆ 0.721574 ┆ 5        │
│ coda1/7/acheung ┆          ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ …               ┆          ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ /storage/home/h ┆ 0.0      ┆ 0.215968 ┆ 0.707746 ┆ … ┆ 0.188679 ┆ 0.44152  ┆ 1.46194  ┆ 15       │
│ coda1/7/acheung ┆          ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ …               ┆          ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
└─────────────────┴──────────┴──────────┴──────────┴───┴──────────┴──────────┴──────────┴──────────┘

In [138]:
df = df.select(
    "file",
    "end_time",
    (
        pl.concat_list(pl.all().exclude("file", "end_time"))
        .list.to_array(len(df.columns) - 2)
        .alias("embedding")
    ),
).sort("file", "end_time")
X = df.get_column("embedding").to_torch().to(torch.float32)
with torch.no_grad():
    pred = torch.softmax(classifier(X), dim=1)
df = df.with_columns(pl.Series("predictions", pred.numpy().tolist()))

df

shape: (9, 4)
┌─────────────────────────────┬──────────┬────────────────────────────┬────────────────────────────┐
│ file                        ┆ end_time ┆ embedding                  ┆ predictions                │
│ ---                         ┆ ---      ┆ ---                        ┆ ---                        │
│ str                         ┆ i64      ┆ array[f32, 1024]           ┆ list[f64]                  │
╞═════════════════════════════╪══════════╪════════════════════════════╪════════════════════════════╡
│ /storage/home/hcoda1/7/ache ┆ 5        ┆ [0.103568, 2.189981, …     ┆ [5.0815e-22, 1.5232e-21, … │
│ ung…                        ┆          ┆ 0.72603…                   ┆ 4.5…                       │
│ /storage/home/hcoda1/7/ache ┆ 10       ┆ [0.016756, 2.221521, …     ┆ [4.0815e-24, 3.3824e-23, … │
│ ung…                        ┆          ┆ 1.02270…                   ┆ 3.6…                       │
│ /storage/home/hcoda1/7/ache ┆ 15       ┆ [0.007265, 2.535607, …     ┆ [1.0775e-17, 3.0516e-17, … │
│ ung…                        ┆          ┆ 0.70562…                   ┆ 2.1…                       │
│ /storage/home/hcoda1/7/ache ┆ 20       ┆ [0.012647, 2.096784, …     ┆ [1.2913e-22, 1.6474e-20, … │
│ ung…                        ┆          ┆ 0.66197…                   ┆ 7.7…                       │
│ /storage/home/hcoda1/7/ache ┆ 25       ┆ [0.067312, 2.551396, …     ┆ [1.6528e-19, 8.8323e-20, … │
│ ung…                        ┆          ┆ 0.51356…                   ┆ 2.6…                       │
│ /storage/home/hcoda1/7/ache ┆ 30       ┆ [0.0, 2.141247, …          ┆ [1.7283e-20, 8.0578e-18, … │
│ ung…                        ┆          ┆ 0.903159]                  ┆ 0.0…                       │
│ /storage/home/hcoda1/7/ache ┆ 5        ┆ [0.11128, 0.056397, …      ┆ [1.9022e-13, 1.2241e-11, … │
│ ung…                        ┆          ┆ 0.721574…                  ┆ 0.0…                       │
│ /storage/home/hcoda1/7/ache ┆ 10       ┆ [0.026202, 0.062568, …     ┆ [4.0099e-11, 1.0526e-7, …  │
│ ung…                        ┆          ┆ 1.27204…                   ┆ 8.18…                      │
│ /storage/home/hcoda1/7/ache ┆ 15       ┆ [0.0, 0.215968, … 1.46194] ┆ [2.0014e-11, 5.0843e-11, … │
│ ung…                        ┆          ┆                            ┆ 3.5…                       │
└─────────────────────────────┴──────────┴────────────────────────────┴────────────────────────────┘