# metrics

In [1]:
%load_ext autoreload
%autoreload 2

In [3]:
import os
import json
import pandas as pd
from pathlib import Path

# set the root directory containing all model subdirectories
root_dir = Path("~/p-dsgt_clef2025-0/shared/birdclef/models/2025/v2").expanduser()

# define the list to store rows
rows = []

# loop through each model directory
for model_name in os.listdir(root_dir):
    model_dir = os.path.join(root_dir, model_name)
    results_path = os.path.join(model_dir, "evaluation_results.json")

    if not os.path.isfile(results_path):
        continue

    with open(results_path, "r") as f:
        results = json.load(f)

    for split in ["training_metrics", "validation_metrics"]:
        row = {
            "model_name": results["model_name"],
            "split": "train" if split == "training_metrics" else "val",
            "accuracy": results[split].get("accuracy"),
            "f1_macro": results[split].get("f1_macro"),
            "f1_micro": results[split].get("f1_micro"),
            "f1_weighted": results[split].get("f1_weighted"),
            "recall": results[split].get("recall_macro"),
            "precision_macro": results[split].get("precision_macro"),
            "auc_roc_macro": results[split].get("auc_macro"),
            "auc_roc_weighted": results[split].get("auc_weighted"),
        }
        rows.append(row)

# create a DataFrame
df = pd.DataFrame(rows)

# Save to CSV
output_csv_path = os.path.join(root_dir, "compiled_evaluation_results.csv")
df.to_csv(output_csv_path, index=False)
print(f"Compiled evaluation results saved to: {output_csv_path}")
df.head()

Compiled evaluation results saved to: /storage/home/hcoda1/9/mgustineli3/p-dsgt_clef2025-0/shared/birdclef/models/2025/v2/compiled_evaluation_results.csv

,model_name,split,accuracy,f1_macro,f1_micro,f1_weighted,recall,precision_macro,auc_roc_macro,auc_roc_weighted
0,Perch,train,0.950306,0.946546,0.950306,0.950564,0.941420,0.961841,0.999771,0.999494
1,Perch,val,0.869037,0.857100,0.869037,0.869391,0.844008,0.881291,0.997341,0.995772
2,BirdNET,train,0.907387,0.912697,0.907387,0.907533,0.918057,0.914083,0.999506,0.998833
3,BirdNET,val,0.872774,0.876026,0.872774,0.872980,0.878367,0.880500,0.998627,0.997289
4,BirdSetConvNeXT,train,0.951904,0.943956,0.951904,0.951963,0.942220,0.955825,0.999864,0.999665

In [4]:
df.head(20)

,model_name,split,accuracy,f1_macro,f1_micro,f1_weighted,recall,precision_macro,auc_roc_macro,auc_roc_weighted
0,Perch,train,0.950306,0.946546,0.950306,0.950564,0.941420,0.961841,0.999771,0.999494
1,Perch,val,0.869037,0.857100,0.869037,0.869391,0.844008,0.881291,0.997341,0.995772
2,BirdNET,train,0.907387,0.912697,0.907387,0.907533,0.918057,0.914083,0.999506,0.998833
3,BirdNET,val,0.872774,0.876026,0.872774,0.872980,0.878367,0.880500,0.998627,0.997289
4,BirdSetConvNeXT,train,0.951904,0.943956,0.951904,0.951963,0.942220,0.955825,0.999864,0.999665
5,BirdSetConvNeXT,val,0.884121,0.876061,0.884121,0.884546,0.864694,0.902934,0.998011,0.997030
6,BirdSetEfficientNetB1,train,0.849360,0.830809,0.849360,0.849885,0.818396,0.862127,0.997622,0.995729
7,BirdSetEfficientNetB1,val,0.819137,0.776498,0.819137,0.819658,0.764284,0.814505,0.995600,0.993062
8,RanaSierraeCNN,train,0.250203,0.237936,0.250203,0.233954,0.243589,0.296558,0.901446,0.849773
9,RanaSierraeCNN,val,0.243411,0.220684,0.243411,0.227053,0.226900,0.273895,0.893883,0.842992